pipeline {
    agent any
    environment {
        branch = 'master'
        scmUrl = 'https://github.com/upuldi/spring-boot-rest.git'
        serverPort = '8080'
        developmentServer = '192.168.1.15'
        stagingServer = 'staging-myproject.mycompany.com'
        productionServer = 'production-myproject.mycompany.com'
    }
    
    tools {
		maven 'M3'
	}

	
    stages {
        stage('checkout git') {
            steps {
                git branch: branch, credentialsId: 'GitCredentials', url: scmUrl
            }
        }

        stage('build') {
            steps {
                sh 'mvn clean package -DskipTests=true'
            }
        }

        stage ('test') {
            steps {
                parallel (
                    "unit tests": { sh 'mvn test' },
                    //"integration tests": { sh 'mvn integration-test' }
                )
            }
        }

        stage('deploy development'){
            steps {
                deploy(developmentServer, serverPort)
                
                httpRequest httpMode: 'POST', url: "http://192.168.1.15:9090/shutdown", validResponseCodes: '200,408'
                sshagent(['RemoteCredentials']) {
                    sh "scp target/*.jar root@192.168.1.15:/opt/jenkins-demo.jar"
                    sh "ssh udoluweera@192.168.1.15 nohup java -Dserver.port=9090 -jar /opt/jenkins-demo.jar &"
                }
                retry (3) {
                    sleep 5
                    httpRequest url:"http://192.168.1.15:9090/health", validResponseCodes: '200', validResponseContent: '"status":"UP"'
                }
            }
        }

    }
    post {
        failure {
            mail to: 'team@example.com', subject: 'Pipeline failed', body: "${env.BUILD_URL}"
        }
    }
}



def deploy(def server, def port) {


    
}
