 
pipeline {

	agent any

    environment {
        varibleDefinition = "foo"
    }
   
	tools {
		maven 'M3'
	}

	stages {
	
        stage('Varible from environment') {
			steps {
				sh 'echo ${varibleDefinition}'
			}
		}

        
        stage('Varible from definition') {
            steps {
                script {
                    def commit = sh (returnStdout: true, script: '''echo hi
    echo bye | grep -o "e"
    date
    echo lol''').split()
                    echo "${commit[-1]} "            
                }
            }
        }
        
        stage('Uname') {
            steps {
                script {
                    def uname = sh (returnStdout: true, script: '''uname -r''').split()
                    echo "${uname} "            
                }
            }
        }
        
        
        stage('Curl') {
            steps {
                script {
                    def curl = sh (returnStdout: true, script: """ 
                    
                    
                    curl -S -i -k -X POST http://www.google.com -H \"Content-Type: application/json\" -H \"Accept: application/json\" -d @request1.json | grep token | cut -d, -f1 | cut -d\" -f4
                    
                    
                    """).split()
                    echo "${curl} "            
                }
            }
        }
        
        
        
        
        
        
        
        
    
    }
    
    post { 
            always { 
                echo 'Finishing .....'
            }
        }    
    
}
