 
pipeline {

	agent any

	tools {
		maven 'M3'
	}

	stages {

        stage('Keeping a response from a script in a variable ......') {
        
            def commit = sh (returnStdout: true, script: '''echo hi
            echo bye | grep -o "e"
            date
            echo lol''').split()

            echo "${commit[-1]} "
    
			steps {
			
                def ret = sh(script: 'uname', returnStdout: true)
                echo 'Finishing .....'

            }

			
    }
    
    post { 
            always { 
                echo 'Finishing .....'
            }
        }    
    
}
