pipeline {

    stages {

        stage('Checkout external proj') {
            steps {
                git branch: 'my_specific_branch',
                    credentialsId: 'my_cred_id',
                    url: 'ssh://git@test.com/proj/test_proj.git'
                sh "ls -lat"
            }
        }

        stage('Checkout code') {
            steps {
                checkout scm
            }
        }

    }
}

