 
pipeline {

	agent any

	tools {
		maven 'M3'
	}

	stages {

		stage('Checkout') {
			steps {
                git 'https://github.com/upuldi/spring-boot-rest.git'
			}
		}

        stage('Build') {
			steps {
				sh 'mvn clean compile'
			}
		}

        stage('Test') {
			steps {
				sh 'mvn test'
				junit '**/target/surefire-reports/TEST-*.xml'
			}
		}
			
			
    }
}
