 
pipeline {

	agent any

	stages {

		stage('First Stage') {

			steps {

				echo "Hello World...."
				echo "This will be the second stage as the checking out the JenkinsFile is the first stage..."
			}

		}

	}
	


}
